### ISSUE TITLE
Comments don't work in Firefox

### ISSUE THREAD

**Issue by sppmacd** [Adam-Ratajczak/AdamAnimeArray#11]
This is because the page is reloaded before a comment write request is sent:
```js
LoginMan.writeComment(AnimeID, 0, input.value)
input.value = ""

ev.preventDefault()
window.location.reload()
```
![image](https://user-images.githubusercontent.com/42967349/236633204-2aec1c39-acd6-4f59-85eb-1200a92ffe24.png)

**Comment by Adam-Ratajczak** [comment]
Very hack solution has been already commited ;-)

**Comment by Adam-Ratajczak** [comment]
Firefox isn't chromium-like browser on which I work so more tests would be very appreciated heh...
