### ISSUE TITLE
Cannot remove anime from watchlist on homepage

### ISSUE THREAD

**Issue by sppmacd** [Adam-Ratajczak/AdamAnimeArray#13]
This button refreshes page, but doesn't remove anime from watchlist:
![image](https://github.com/Adam-Ratajczak/AdamAnimeArray/assets/42967349/94dab54a-cb5c-476c-88fe-bbdd5cf3846b)

This is Firefox-specific. Probably the same bug with reloading as previously.

**Comment by Adam-Ratajczak** [comment]
Problem should not occur now
